CREATE TABLE professor(
  idprof SERIAL NOT NULL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  dtnas DATE NOT NULL,
  dtcontratacao DATE NOT NULL,
  idtit INT NOT NULL REFERENCES titulacao (idtit),
  idinst INT NOT NULL REFERENCES instituicao (idinst)
);

INSERT INTO titulacao (descricao) VALUES ('ESPECIALISTA'), ('MESTRE'), ('DOUTOR');

Ύ descricao = especialista (TITULACAO)

SELECT * FROM TITULACAO WHERE DESCRICAO = ESPECIALISTA

CREATE TABLE TITULACAO(
  IDTIT SERIAL NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR(30) NOT NULL
)

σ DTCONTRATACAO > "2010-01-01" (PROFESSOR)

SELECT * FROM `PROFESSOR` WHERE 'DTCONTRATACAO' > "2010-01-01"

SELECT * FROM `INSTITUICAO` WHERE UPPER('nome') like '%Universidade%'


σ NOME LIKE '%UNIVERSIDADE%' (INSTITUICAO)
